### ISSUE TITLE
Does SO Mobile Map Widget in posts?

### ISSUE THREAD

**Issue by maderemark** [senlin/so-mobile-map-widget#5]
Hi!

Does SO Mobile Map Widget in posts? I have a WordPress site where I create posts with special offers for businesses that I'd like to include a map showing their location and driving directions on mobile.

I don't believe I can use widgets in individual posts. Can SO Mobile Map Widget create short code that I can add into a post? If not, can you recommend another plugin that might?

Thanks!

Mark

**Comment by senlin** [comment]
Hi Mark,

It indeed is impossible to directly add a widget to a Post; the only thing possible is to make a widget area available for Single Posts, but that would not help you in what you're trying to accomplish.

It could be possible to do it as a shortcode perhaps, but my preferred way would be to build a custom meta box (using the [Meta Box](http://metabox.io) plugin) and add the different variables through there.

Does that help you?

Piet
