### ISSUE TITLE
SO Mobile Map Widget change the layout in genesis framework

### ISSUE THREAD

**Issue by oassismx** [senlin/so-mobile-map-widget#6]
Hi, After I installed the pluggin, the layouts of my genesis sample theme started to behave rarely changing the layout.   I deactivate the plugging and uninstalled and my layout themes still look bad.  I contacted the studiopress support and asked me to contact you.   Hope you can help me to fix this.

**Comment by senlin** [comment]
Hi Thanks for the report.
If the layout is still changed even after deactivating the plugin then that usually is a sign that it is not related to the plugin you just deactivated. Furthermore the plugin does not do anything with the theme's layout.
We don't mind to take a quick look at your site, what is your URL?

**Comment by oassismx** [comment]
Thank you very much.  Here is it: serviciodegruas.mx  I am totally new in
this and i just start building my site
thank you Piet

**Comment by oassismx** [comment]
The layout for the other pages should be the same that the homepage

**Comment by senlin** [comment]
The problem most likely is related to how your theme calls the CDN. All links (other than the home page) now have a double forward slash.

See for example 
homepage: http://serviciodegruas.mx/wp-content/themes/genesis-sample/style.css?ver=2.1.2
other pages: http://cdn.serviciodegruas.mx//wp-content/themes/genesis-sample/style.css?ver=2.1.2

Nothing to do with the SO Mobile Map Widget plugin, probably just unlucky that you were trying out multiple things at the same time. I'll be closing this out.

**Comment by oassismx** [comment]
Great I already deactivate the CDN pluggin... thanks Piet and sorry for the
missleading issue
