### ISSUE TITLE
SO Mobile Map Widget - Show two locations on one map?

### ISSUE THREAD

**Issue by PhoenixMaximus** [senlin/so-mobile-map-widget#7]
Is there currently a way to do this? If not, are there any plans for this feature in future updates?

Thanks

**Comment by senlin** [comment]
It currently is not possible.

The thing with adding this in the future is that if we add the possibility to add two locations then the next person asks whether it is possible to add 3 (or more) locations and then soon thereafter the different locations are so spread out that the map needs to become scrollable (which indeed is impossible with a static map image).

Therefore I think it is very unlikely that we will add the possibility to add 2 (or more) locations, as the whole point of this widget is to show a static map image and therefore be lightweight and mobile optimised.

What you could do is to implement a script like [MobileDetect](http://mobiledetect.net) to implement a traditional map for lap/desktops and keep the SO Mobile Map Widget for tablets/smartphones.

**Comment by PhoenixMaximus** [comment]
Hi, thanks for your answer.
I'm looking to add two nearby locations for a client who has two offices. I want the map to show these locations to all users, not just desktop. No big deal, I'll keep searching for something that can meet my needs. Thanks.
