### ISSUE TITLE
Plugin works but not with Custom Content Shortcode variable

### ISSUE THREAD

**Issue by coolicious** [senlin/so-mobile-map-widget#8]
Hey,

this plugin is perfect but I cant use it. 

I have to show the map on several pages with "dynamic" maps which gets the adress via a custom content shortcode like [field adress]. But your plugin cant read it or something.

What can I do now? Can you maybe fix that? That will be awesome! :)

**Comment by senlin** [comment]
Hi @coolicious glad to hear that you like the plugin :)

Regarding your question, you are looking for a way to dynamically add the address via a shortcode?

It's understandable that my plugin cannot read your shortcode, also usually shortcodes don't work in widgets...
You could customise the plugin to take dynamic input of addresses, but I would not do that via a shortcode and instead via custom meta data, which is much more suitable for that. The ACF plugin comes to mind.

If you have a look at [this site](https://www.wogen.com/about-wogen/locations-contact-us/) and click through on on an office location, you will see an adapted version of the plugin at work. There we also have used custom meta data for the office addresses, which - as you can see - works excellent!

Hope this helps and apologies for the late response.

**Comment by coolicious** [comment]
Hey,

thanks for the response.

Ok I get it, it does work better with the ACF plugin. I use the ACF plugin on my website for several things but I can’t get an idea in which way I can achieve my goal to show the map via your plugin in dependency of the content.

Can I achieve that without coding?

Best regards

**Comment by senlin** [comment]
To achieve that without coding is not going to be possible.

I'm available for hire though to customise it for you :)
